// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using ProgettoIndustriale.Type.Domain;

namespace ProgettoIndustriale.Type.Domain
{
    public partial class ApiCallsLogs
    {
        public ApiCallsLogs()
        {
        }
        
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Column("apiCallName")]
        public string ApiCallName { get; set; }
        [Column("callFrequency")]
        public string CallFrequency { get; set; }
        [Column("lastSuccessfulRun")]
        public DateTime LastSuccessfulRun { get; set; }
        
    }
}