// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using ProgettoIndustriale.Type.Domain;

namespace ProgettoIndustriale.Type.Domain
{
    public partial class Industry
    {
        public Industry()
        {
        }
        
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public int CountActive { get; set; }
        public int IdProvince { get; set; }

        public virtual Province Province { get; set; }   

    }
}