// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using ProgettoIndustriale.Type.Domain;

namespace ProgettoIndustriale.Type.Domain
{
    public partial class Provincia
    {
        public Provincia()
        {
        }
        
        [Key]
        public string Codice { get; set; }
        public string Nome { get; set; }
        public string Sigla { get; set; }
        public string Regione { get; set; }
    }
}