// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using ProgettoIndustriale.Type.Domain;

namespace ProgettoIndustriale.Type.Domain
{
    public partial class Province
    {
        public Province()
        {
        }
        
        [Column ("ID_Province")]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public float Altitude { get; set; }
        public float Surface { get; set; }
        public int Residents { get; set; }
        public float PopulationDensity { get; set; }
        public int NCities { get; set; }
        public int IdRegion { get; set; }

        public virtual Region Region { get; set; }
        public virtual ICollection<Industry> Industries { get; set; }
    }
}