// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using ProgettoIndustriale.Type.Domain;

namespace ProgettoIndustriale.Type.Domain
{
    public partial class Region
    {
        public Region()
        {
        }

        [Column("ID_region")]
        public int Id { get; set; }

        [Column("name")]
        public string Name { get; set; }

        [Column("COD_macrozone")]
        public int IdMacroZone { get; set; }

        public virtual MacroZone MacroZone { get; set; }
        public virtual ICollection<Province> Provinces { get; set; }    
    }
}